/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package books;

import org.springframework.boot.test.context.SpringBootTest;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
class AppTest {
//
//    @Autowired
//    BookRepository bookRepository;
//
//    @Test
//    void testBookRepository() {
//        long count = bookRepository.count();
//        assertThat(count).isGreaterThan(0);
//    }
//
//    @Test
//    void contextLoads() {}
}
