/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.basic;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class SampleTest {
    @Test void testGetMessage() {
        assertEquals("Hello      World!", "Hello      World!");
    }
}
